export const FETCH_LAPS_SUCCESS = "FETCH_LAPS_SUCCESS";
export const FETCH_LAPS_STARTED = "FETCH_LAPS_STARTED";
export const FETCH_LAPS_FAILED = "FETCH_LAPS_FAILED";

export const SET_ACTIVE_SERVICE = "SET_ACTIVE_SERVICE";

export const LAPS_VIEWMODELS_AVAILABLE = "LAPS_VIEWMODELS_AVAILABLE";